feat: add enable_turbo variable
araise-dev/TableBundle pull request #15
Opened 2023-11-14 08:33 UTC by Ruesa18

Introduce new `enable_turbo` variable to control whether or not to use turbo on tables and other content

2023-11-16 12:44 UTC, tuxes3 requested changes

2023-11-16 12:44 UTC, tuxes3 commented on src/DependencyInjection/araiseTableExtension.php
> +        $container->setParameter('araise.enable_turbo', $config['enable_turbo']);
this is not needed

2023-11-16 12:44 UTC, tuxes3 commented on src/Resources/views/tailwind_2_layout.html.twig
> +            <turbo-frame id="whatwedo_table_{{ table.identifier }}" data-turbo="{{ araise_turbo_enabled ? 'true' : 'false' }}" target="_top" {{ stimulus_action('@araise/table-bundle/table_select', 't
create another twig extension for the parameter `araise_table.enable_turbo` and use this one.

2023-11-16 12:44 UTC, tuxes3 commented on src/DependencyInjection/araiseTableExtension.php
> -        $doctrineConfig = $container->getExtensionConfig('doctrine_migrations');
why did you remove this part?

2023-11-16 15:35 UTC, Ruesa18 commented on src/DependencyInjection/araiseTableExtension.php
> -        $doctrineConfig = $container->getExtensionConfig('doctrine_migrations');
That was an accident 😅

2023-11-21 17:15 UTC, tuxes3 approved these changes

2023-11-21 17:15 UTC, merged