feat: allow batch action to open multiple urls in new tab
araise-dev/TableBundle pull request #19
Opened 2023-11-14 18:05 UTC by dowitsch

2023-11-15 09:47 UTC, tuxes3 requested changes

2023-11-15 22:04 UTC, dowitsch commented on src/Resources/assets/controllers/table_select_controller.js
> +                if (data.open && Array.isArray(data.open)) {
I disagree. Imo it only makes is more confusing if both is possible and on one way you can specify openType and so on and on the other way you cant. if you want to only open one url you can only pass one entry

2023-11-15 22:04 UTC, dowitsch commented on src/Resources/assets/controllers/table_select_controller.js
> +                        window.open(url, '_blank');
Done :heavy_check_mark:

2023-11-16 12:45 UTC, tuxes3 commented on src/Resources/assets/controllers/table_select_controller.js
> +                if (data.open && Array.isArray(data.open)) {
👍  agree

2023-11-16 12:45 UTC, tuxes3 approved these changes

2023-11-16 12:45 UTC, merged